In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [4]:
df.area

0      7420
1      8960
2      9960
3      7500
4      7420
       ...
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64

In [5]:
df[['price','area']]

        price  area
0    13300000  7420
1    12250000  8960
2    12250000  9960
3    12215000  7500
4    11410000  7420
..        ...   ...
540   1820000  3000
541   1767150  2400
542   1750000  3620
543   1750000  2910
544   1750000  3850

[545 rows x 2 columns]

In [6]:
# row data from indexing value fetch
# loc [location]
df.loc[0]

price                13300000
area                     7420
bedrooms                    4
bathrooms                   2
stories                     3
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     2
prefarea                  yes
furnishingstatus    furnished
Name: 0, dtype: object

In [7]:
# row data from indexing value fetch
df.loc[3]

price                12215000
area                     7500
bedrooms                    4
bathrooms                   2
stories                     2
mainroad                  yes
guestroom                  no
basement                  yes
hotwaterheating            no
airconditioning           yes
parking                     3
prefarea                  yes
furnishingstatus    furnished
Name: 3, dtype: object

In [8]:
df.iloc[0]

price                13300000
area                     7420
bedrooms                    4
bathrooms                   2
stories                     3
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     2
prefarea                  yes
furnishingstatus    furnished
Name: 0, dtype: object

In [9]:
# multiple rows
df.loc[[0,3,7]]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished

In [10]:
df.iloc[[2,8,13]]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished

In [11]:
# filtering row
df[df['price']> 10150000]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished

In [12]:
# adding new columns
#df['phone_no']=[10,20,40,57,20]
df['phone_no']=10
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,phone_no
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,10
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,10
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,10
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,10
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished,10
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished,10
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished,10
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished,10
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished,10

In [13]:
# deletind a column

df = df.drop(columns=['phone_no'])
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [14]:
# insert

df.insert(3,'phone_no',[10]*545)
print(df)

        price  area  bedrooms  phone_no  bathrooms  stories mainroad  \
0    13300000  7420         4        10          2        3      yes
1    12250000  8960         4        10          4        4      yes
2    12250000  9960         3        10          2        2      yes
3    12215000  7500         4        10          2        2      yes
4    11410000  7420         4        10          1        2      yes
..        ...   ...       ...       ...        ...      ...      ...
540   1820000  3000         2        10          1        1      yes
541   1767150  2400         3        10          1        1       no
542   1750000  3620         2        10          1        1      yes
543   1750000  2910         3        10          1        1       no
544   1750000  3850         3        10          1        2      yes

    guestroom basement hotwaterheating airconditioning  parking prefarea  \
0          no       no              no             yes        2      yes
1          no       no              no             yes        3       no
2          no      yes              no              no        2      yes
3          no      yes              no             yes        3      yes
4         yes      yes              no             yes        2       no
..        ...      ...             ...             ...      ...      ...
540        no      yes              no              no        2       no
541        no       no              no              no        0       no
542        no       no              no              no        0       no
543        no       no              no              no        0       no
544        no       no              no              no        0       no

    furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
..               ...
540      unfurnished
541   semi-furnished
542      unfurnished
543        furnished
544      unfurnished

[545 rows x 14 columns]

In [15]:
# rename
#                       old       new
df = df.rename(columns={'area':'location'})
df

,price,location,bedrooms,phone_no,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,10,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,10,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,10,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,10,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,10,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,10,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,10,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,10,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,10,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,10,1,2,yes,no,no,no,no,0,no,unfurnished

In [16]:
# delete another method

del df['phone_no']
df

,price,location,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [17]:
# deleting a row from df

df = df.drop(3)
df

,price,location,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [21]:
# update a value in df

df.loc[1,"location"]=2000
df

,price,location,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,2000,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished