In [ ]:
# Merging aur Joining DataFrames

In [1]:
import pandas as pd

In [ ]:
# Step 1: Read CSV Files

In [2]:
# First DataFrame
df1 = pd.DataFrame({
    'id': [1,2,3,4,5,6,7,8,9,10,
           11,12,13,14,15,16,17,18,19,20],
    
    'name': ['Prerna','Rahul','Amit','Sneha','Karan',
             'Neha','Arjun','Pooja','Vikas','Riya',
             'Ankit','Simran','Rohit','Meena','Yash',
             'Kriti','Dev','Tina','Aryan','Nisha'],
    
    'city': ['Ahmedabad','Delhi','Mumbai','Pune','Surat',
             'Jaipur','Chennai','Kolkata','Bhopal','Indore',
             'Lucknow','Patna','Nagpur','Rajkot','Vadodara',
             'Goa','Hyderabad','Noida','Kanpur','Agra']
})

In [3]:
print("DataFrame 1")
print(df1)

DataFrame 1
    id    name       city
0    1  Prerna  Ahmedabad
1    2   Rahul      Delhi
2    3    Amit     Mumbai
3    4   Sneha       Pune
4    5   Karan      Surat
5    6    Neha     Jaipur
6    7   Arjun    Chennai
7    8   Pooja    Kolkata
8    9   Vikas     Bhopal
9   10    Riya     Indore
10  11   Ankit    Lucknow
11  12  Simran      Patna
12  13   Rohit     Nagpur
13  14   Meena     Rajkot
14  15    Yash   Vadodara
15  16   Kriti        Goa
16  17     Dev  Hyderabad
17  18    Tina      Noida
18  19   Aryan     Kanpur
19  20   Nisha       Agra

In [4]:
# Second DataFrame
df2 = pd.DataFrame({
    'id': [1,2,3,4,5,6,7,8,9,10,
           11,12,13,14,15,16,17,18,19,20],
    
    'salary': [25000,30000,35000,28000,40000,
               32000,45000,38000,29000,41000,
               36000,27000,50000,33000,39000,
               42000,46000,31000,37000,34000],
    
    'department': ['IT','HR','Finance','Marketing','IT',
                   'Sales','Finance','HR','IT','Marketing',
                   'Sales','HR','Finance','IT','Marketing',
                   'Sales','IT','Finance','HR','Marketing']
})

In [5]:
print("\nDataFrame 2")
print(df2)

DataFrame 2
    id  salary department
0    1   25000         IT
1    2   30000         HR
2    3   35000    Finance
3    4   28000  Marketing
4    5   40000         IT
5    6   32000      Sales
6    7   45000    Finance
7    8   38000         HR
8    9   29000         IT
9   10   41000  Marketing
10  11   36000      Sales
11  12   27000         HR
12  13   50000    Finance
13  14   33000         IT
14  15   39000  Marketing
15  16   42000      Sales
16  17   46000         IT
17  18   31000    Finance
18  19   37000         HR
19  20   34000  Marketing

In [ ]:
# MERGE
result = pd.merge(df1, df2, on='id')

print("\nMerged DataFrame")
print(result)

Merged DataFrame
    id    name       city  salary department
0    1  Prerna  Ahmedabad   25000         IT
1    2   Rahul      Delhi   30000         HR
2    3    Amit     Mumbai   35000    Finance
3    4   Sneha       Pune   28000  Marketing
4    5   Karan      Surat   40000         IT
5    6    Neha     Jaipur   32000      Sales
6    7   Arjun    Chennai   45000    Finance
7    8   Pooja    Kolkata   38000         HR
8    9   Vikas     Bhopal   29000         IT
9   10    Riya     Indore   41000  Marketing
10  11   Ankit    Lucknow   36000      Sales
11  12  Simran      Patna   27000         HR
12  13   Rohit     Nagpur   50000    Finance
13  14   Meena     Rajkot   33000         IT
14  15    Yash   Vadodara   39000  Marketing
15  16   Kriti        Goa   42000      Sales
16  17     Dev  Hyderabad   46000         IT
17  18    Tina      Noida   31000    Finance
18  19   Aryan     Kanpur   37000         HR
19  20   Nisha       Agra   34000  Marketing

In [ ]:
# 2. Different Types of Merge
'''
Inner Merge
Only matching rows come.
'''

pd.merge(df1, df2, on='id', how='inner')

    id    name       city  salary department
0    1  Prerna  Ahmedabad   25000         IT
1    2   Rahul      Delhi   30000         HR
2    3    Amit     Mumbai   35000    Finance
3    4   Sneha       Pune   28000  Marketing
4    5   Karan      Surat   40000         IT
5    6    Neha     Jaipur   32000      Sales
6    7   Arjun    Chennai   45000    Finance
7    8   Pooja    Kolkata   38000         HR
8    9   Vikas     Bhopal   29000         IT
9   10    Riya     Indore   41000  Marketing
10  11   Ankit    Lucknow   36000      Sales
11  12  Simran      Patna   27000         HR
12  13   Rohit     Nagpur   50000    Finance
13  14   Meena     Rajkot   33000         IT
14  15    Yash   Vadodara   39000  Marketing
15  16   Kriti        Goa   42000      Sales
16  17     Dev  Hyderabad   46000         IT
17  18    Tina      Noida   31000    Finance
18  19   Aryan     Kanpur   37000         HR
19  20   Nisha       Agra   34000  Marketing

In [8]:
'''
Left Merge
All rows from left dataframe.
'''

pd.merge(df1, df2, on='id', how='left')

    id    name       city  salary department
0    1  Prerna  Ahmedabad   25000         IT
1    2   Rahul      Delhi   30000         HR
2    3    Amit     Mumbai   35000    Finance
3    4   Sneha       Pune   28000  Marketing
4    5   Karan      Surat   40000         IT
5    6    Neha     Jaipur   32000      Sales
6    7   Arjun    Chennai   45000    Finance
7    8   Pooja    Kolkata   38000         HR
8    9   Vikas     Bhopal   29000         IT
9   10    Riya     Indore   41000  Marketing
10  11   Ankit    Lucknow   36000      Sales
11  12  Simran      Patna   27000         HR
12  13   Rohit     Nagpur   50000    Finance
13  14   Meena     Rajkot   33000         IT
14  15    Yash   Vadodara   39000  Marketing
15  16   Kriti        Goa   42000      Sales
16  17     Dev  Hyderabad   46000         IT
17  18    Tina      Noida   31000    Finance
18  19   Aryan     Kanpur   37000         HR
19  20   Nisha       Agra   34000  Marketing

In [9]:
'''
Right Merge
All rows from right dataframe.
'''

pd.merge(df1, df2, on='id', how='right')

    id    name       city  salary department
0    1  Prerna  Ahmedabad   25000         IT
1    2   Rahul      Delhi   30000         HR
2    3    Amit     Mumbai   35000    Finance
3    4   Sneha       Pune   28000  Marketing
4    5   Karan      Surat   40000         IT
5    6    Neha     Jaipur   32000      Sales
6    7   Arjun    Chennai   45000    Finance
7    8   Pooja    Kolkata   38000         HR
8    9   Vikas     Bhopal   29000         IT
9   10    Riya     Indore   41000  Marketing
10  11   Ankit    Lucknow   36000      Sales
11  12  Simran      Patna   27000         HR
12  13   Rohit     Nagpur   50000    Finance
13  14   Meena     Rajkot   33000         IT
14  15    Yash   Vadodara   39000  Marketing
15  16   Kriti        Goa   42000      Sales
16  17     Dev  Hyderabad   46000         IT
17  18    Tina      Noida   31000    Finance
18  19   Aryan     Kanpur   37000         HR
19  20   Nisha       Agra   34000  Marketing

In [10]:
'''
Outer Merge
All rows from both dataframes.
'''

pd.merge(df1, df2, on='id', how='outer')

    id    name       city  salary department
0    1  Prerna  Ahmedabad   25000         IT
1    2   Rahul      Delhi   30000         HR
2    3    Amit     Mumbai   35000    Finance
3    4   Sneha       Pune   28000  Marketing
4    5   Karan      Surat   40000         IT
5    6    Neha     Jaipur   32000      Sales
6    7   Arjun    Chennai   45000    Finance
7    8   Pooja    Kolkata   38000         HR
8    9   Vikas     Bhopal   29000         IT
9   10    Riya     Indore   41000  Marketing
10  11   Ankit    Lucknow   36000      Sales
11  12  Simran      Patna   27000         HR
12  13   Rohit     Nagpur   50000    Finance
13  14   Meena     Rajkot   33000         IT
14  15    Yash   Vadodara   39000  Marketing
15  16   Kriti        Goa   42000      Sales
16  17     Dev  Hyderabad   46000         IT
17  18    Tina      Noida   31000    Finance
18  19   Aryan     Kanpur   37000         HR
19  20   Nisha       Agra   34000  Marketing

In [11]:
# 3. If Column Names are Different

df1 = pd.DataFrame({
    'student_id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})

In [12]:
df2 = pd.DataFrame({
    'id': [1, 2, 3],
    'marks': [90, 85, 88]
})

In [13]:
# use

pd.merge(df1, df2,
         left_on='student_id',
         right_on='id')

   student_id name  id  marks
0           1    A   1     90
1           2    B   2     85
2           3    C   3     88

In [14]:
# 4. Joining DataFrames (join())

df1 = pd.DataFrame({
    'name': ['Prerna', 'Rahul', 'Amit']
}, index=[1, 2, 3])

In [15]:
df2 = pd.DataFrame({
    'salary': [25000, 30000, 40000]
}, index=[1, 2, 3])

In [16]:
result = df1.join(df2)

print(result)

     name  salary
1  Prerna   25000
2   Rahul   30000
3    Amit   40000

In [36]:
# 5. Merge CSV Files
print(df1.columns)
print(df2.columns)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')
Index(['first', 'last', 'address', 'city', 'phone'], dtype='object')

In [37]:
df1 = pd.read_csv("housing.csv")
df1

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [38]:
df2 = pd.read_csv("owners.csv")
df2

      first      last        address      city       phone
0      Jane    Garcia    643 2nd Ave    Boston  9325763815
1      Emma     Smith  5399 Maple St   Houston  9084802186
2       Bob     Smith  5016 Cedar St    Boston  8985554810
3     Alice     Brown   3417 1st Ave  San Jose  2684754835
4    Olivia    Miller    4543 Oak St  San Jose  2339613320
..      ...       ...            ...       ...         ...
495     Bob  Martinez  2070 Broadway    Dallas  2613112172
496     Bob     Davis    3017 Oak St    Dallas  9558994821
497    John  Martinez   4471 Main St    Austin  5995458733
498   David     Smith  7427 Cedar St   Chicago  3295918401
499    Emma     Smith   3791 Main St    Dallas  6622608358

[500 rows x 5 columns]

In [39]:
# result = pd.merge(df1, df2, on='id')
# print(result)

In [40]:
'''
Difference Between Merge and Join

| Merge         | Join        |
| ------------- | ----------- |
| Uses columns  | Uses index  |
| More flexible | Simpler     |
| `pd.merge()`  | `df.join()` |

'''

'\nDifference Between Merge and Join\n\n| Merge         | Join        |\n| ------------- | ----------- |\n| Uses columns  | Uses index  |\n| More flexible | Simpler     |\n| `pd.merge()`  | `df.join()` |\n\n'