In [1]:
# Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/PhishingData.csv')

In [3]:
df

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,1,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,2,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,3,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,4,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,5,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11050,11051,1,-1,1,-1,1,1,1,1,-1,...,-1,-1,1,1,-1,-1,1,1,1,1
11051,11052,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,-1,1,-1
11052,11053,1,-1,1,1,1,-1,1,-1,-1,...,1,1,1,1,1,-1,1,0,1,-1
11053,11054,-1,-1,1,1,1,-1,-1,-1,1,...,-1,1,1,1,1,-1,1,1,1,-1
11054,11055,-1,-1,1,1,1,-1,-1,-1,1,...,1,1,-1,1,-1,-1,-1,1,-1,-1

In [ ]:
'''
Operation use Pandas
1. df. head()
2. df.tail()
3. df.shape
4. df.columns
5. df.size
6. dtype
7. values
8. index
'''

In [ ]:
df.head(5)

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,1,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,2,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,3,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,4,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,5,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [5]:
df.tail(5)

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
11050,11051,1,-1,1,-1,1,1,1,1,-1,...,-1,-1,1,1,-1,-1,1,1,1,1
11051,11052,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,-1,1,-1
11052,11053,1,-1,1,1,1,-1,1,-1,-1,...,1,1,1,1,1,-1,1,0,1,-1
11053,11054,-1,-1,1,1,1,-1,-1,-1,1,...,-1,1,1,1,1,-1,1,1,1,-1
11054,11055,-1,-1,1,1,1,-1,-1,-1,1,...,1,1,-1,1,-1,-1,-1,1,-1,-1

In [6]:
df.columns

Index(['index ', 'having_IPhaving_IP_Address ', 'URLURL_Length ',
       'Shortining_Service ', 'having_At_Symbol ', 'double_slash_redirecting ',
       'Prefix_Suffix ', 'having_Sub_Domain ', 'SSLfinal_State ',
       'Domain_registeration_length ', 'Favicon ', 'port ', 'HTTPS_token ',
       'Request_URL ', 'URL_of_Anchor ', 'Links_in_tags ', 'SFH ',
       'Submitting_to_email ', 'Abnormal_URL ', 'Redirect ', 'on_mouseover ',
       'RightClick ', 'popUpWidnow ', 'Iframe ', 'age_of_domain ',
       'DNSRecord ', 'web_traffic ', 'Page_Rank ', 'Google_Index ',
       'Links_pointing_to_page ', 'Statistical_report ', 'Result'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   index                         11055 non-null  int64
 1   having_IPhaving_IP_Address    11055 non-null  int64
 2   URLURL_Length                 11055 non-null  int64
 3   Shortining_Service            11055 non-null  int64
 4   having_At_Symbol              11055 non-null  int64
 5   double_slash_redirecting      11055 non-null  int64
 6   Prefix_Suffix                 11055 non-null  int64
 7   having_Sub_Domain             11055 non-null  int64
 8   SSLfinal_State                11055 non-null  int64
 9   Domain_registeration_length   11055 non-null  int64
 10  Favicon                       11055 non-null  int64
 11  port                          11055 non-null  int64
 12  HTTPS_token                   11055 non-null  int64
 13  Request_URL                   11055 non-null  int64
 14  URL_of_Anchor                 11055 non-null  int64
 15  Links_in_tags                 11055 non-null  int64
 16  SFH                           11055 non-null  int64
 17  Submitting_to_email           11055 non-null  int64
 18  Abnormal_URL                  11055 non-null  int64
 19  Redirect                      11055 non-null  int64
 20  on_mouseover                  11055 non-null  int64
 21  RightClick                    11055 non-null  int64
 22  popUpWidnow                   11055 non-null  int64
 23  Iframe                        11055 non-null  int64
 24  age_of_domain                 11055 non-null  int64
 25  DNSRecord                     11055 non-null  int64
 26  web_traffic                   11055 non-null  int64
 27  Page_Rank                     11055 non-null  int64
 28  Google_Index                  11055 non-null  int64
 29  Links_pointing_to_page        11055 non-null  int64
 30  Statistical_report            11055 non-null  int64
 31  Result                        11055 non-null  int64
dtypes: int64(32)
memory usage: 2.7 MB

In [8]:
df.describe()

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
count,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,...,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000,11055.000000
mean,5528.000000,0.313795,-0.633198,0.738761,0.700588,0.741474,-0.734962,0.063953,0.250927,-0.336771,...,0.613388,0.816915,0.061239,0.377114,0.287291,-0.483673,0.721574,0.344007,0.719584,0.113885
std,3191.447947,0.949534,0.766095,0.673998,0.713598,0.671011,0.678139,0.817518,0.911892,0.941629,...,0.789818,0.576784,0.998168,0.926209,0.827733,0.875289,0.692369,0.569944,0.694437,0.993539
min,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,2764.500000,-1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1.000000,1.000000,-1.000000,-1.000000,0.000000,-1.000000,1.000000,0.000000,1.000000,-1.000000
50%,5528.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,1.000000,-1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,1.000000
75%,8291.500000,1.000000,-1.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,11055.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
# rows and columns total
df.size

353760

In [12]:
df.dtypes

index                           int64
having_IPhaving_IP_Address      int64
URLURL_Length                   int64
Shortining_Service              int64
having_At_Symbol                int64
double_slash_redirecting        int64
Prefix_Suffix                   int64
having_Sub_Domain               int64
SSLfinal_State                  int64
Domain_registeration_length     int64
Favicon                         int64
port                            int64
HTTPS_token                     int64
Request_URL                     int64
URL_of_Anchor                   int64
Links_in_tags                   int64
SFH                             int64
Submitting_to_email             int64
Abnormal_URL                    int64
Redirect                        int64
on_mouseover                    int64
RightClick                      int64
popUpWidnow                     int64
Iframe                          int64
age_of_domain                   int64
DNSRecord                       int64
web_traffic                     int64
Page_Rank                       int64
Google_Index                    int64
Links_pointing_to_page          int64
Statistical_report              int64
Result                          int64
dtype: object

In [13]:
df.values

array([[    1,    -1,     1, ...,     1,    -1,    -1],
       [    2,     1,     1, ...,     1,     1,    -1],
       [    3,     1,     0, ...,     0,    -1,    -1],
       ...,
       [11053,     1,    -1, ...,     0,     1,    -1],
       [11054,    -1,    -1, ...,     1,     1,    -1],
       [11055,    -1,    -1, ...,     1,    -1,    -1]], shape=(11055, 32))

In [14]:
df.index

RangeIndex(start=0, stop=11055, step=1)

In [15]:
# row data from indexing value fetch
# loc [location]
df.loc[0]

index                           1
having_IPhaving_IP_Address     -1
URLURL_Length                   1
Shortining_Service              1
having_At_Symbol                1
double_slash_redirecting       -1
Prefix_Suffix                  -1
having_Sub_Domain              -1
SSLfinal_State                 -1
Domain_registeration_length    -1
Favicon                         1
port                            1
HTTPS_token                    -1
Request_URL                     1
URL_of_Anchor                  -1
Links_in_tags                   1
SFH                            -1
Submitting_to_email            -1
Abnormal_URL                   -1
Redirect                        0
on_mouseover                    1
RightClick                      1
popUpWidnow                     1
Iframe                          1
age_of_domain                  -1
DNSRecord                      -1
web_traffic                    -1
Page_Rank                      -1
Google_Index                    1
Links_pointing_to_page          1
Statistical_report             -1
Result                         -1
Name: 0, dtype: int64

In [17]:
# row data from indexing value fetch
df.loc[3]

index                           4
having_IPhaving_IP_Address      1
URLURL_Length                   0
Shortining_Service              1
having_At_Symbol                1
double_slash_redirecting        1
Prefix_Suffix                  -1
having_Sub_Domain              -1
SSLfinal_State                 -1
Domain_registeration_length     1
Favicon                         1
port                            1
HTTPS_token                    -1
Request_URL                    -1
URL_of_Anchor                   0
Links_in_tags                   0
SFH                            -1
Submitting_to_email             1
Abnormal_URL                    1
Redirect                        0
on_mouseover                    1
RightClick                      1
popUpWidnow                     1
Iframe                          1
age_of_domain                  -1
DNSRecord                      -1
web_traffic                     1
Page_Rank                      -1
Google_Index                    1
Links_pointing_to_page         -1
Statistical_report              1
Result                         -1
Name: 3, dtype: int64

In [ ]:
df.isnull()
# print(df.isnull())

,index,having_IPhaving_IP_Address,URLURL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11050,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11051,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11052,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
df.isnull().sum()

index                           0
having_IPhaving_IP_Address      0
URLURL_Length                   0
Shortining_Service              0
having_At_Symbol                0
double_slash_redirecting        0
Prefix_Suffix                   0
having_Sub_Domain               0
SSLfinal_State                  0
Domain_registeration_length     0
Favicon                         0
port                            0
HTTPS_token                     0
Request_URL                     0
URL_of_Anchor                   0
Links_in_tags                   0
SFH                             0
Submitting_to_email             0
Abnormal_URL                    0
Redirect                        0
on_mouseover                    0
RightClick                      0
popUpWidnow                     0
Iframe                          0
age_of_domain                   0
DNSRecord                       0
web_traffic                     0
Page_Rank                       0
Google_Index                    0
Links_pointing_to_page          0
Statistical_report              0
Result                          0
dtype: int64

In [21]:
'''
Breaking the code
dropna()
drop → remove
na → null/missing values
'''
df.dropna(inplace=True)